site_name: 2.5D Beat 'Em Up Template
site_url: https://sitename.example
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.indexes
    - navigation.expand
    - navigation.footer
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
extra_css:
  - stylesheets/extra.css
nav:
  - Introduction: index.md
  - Releases: releases.md
  - Unity Editor: unity-editor.md
  - Assets: assets.md
  - Scenes: scenes.md
  - Systems:
    - systems/index.md
    - Ability: systems/ability.md
    - Action: systems/action.md
    - Animation: systems/animation.md
    - Audio: systems/audio.md
    - Command: systems/command.md
    - Environment: systems/environment.md
    - Game: systems/game.md
    - Hitbox: systems/hitbox.md
    - Input: systems/input.md
    - Player: systems/player.md
    - UI: systems/ui.md
    - Unit: systems/unit.md
    - Utilities: systems/utilities.md

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - md_in_html

extra:
  #social:
    #- icon: simple/youtube
      #link: https://sitename.example
    #- icon: simple/linkedin
      #link: https://sitename.example
  generator: false

copyright: Copyright &copy; 2025 Arcabidi